"""Auto-generated by apitest — test fixtures."""
import os
import pytest
import httpx


@pytest.fixture(scope="session")
def base_url():
    return os.environ.get("APITEST_BASE_URL", "http://127.0.0.1:59498")


@pytest.fixture(scope="session")
def auth_token():
    token = os.environ.get("APITEST_AUTH_TOKEN", "")
    if not token:
        # In mock mode or without auth config, use a placeholder token
        token = "mock-token-for-testing"
    return token


@pytest.fixture
def client(base_url):
    with httpx.Client(base_url=base_url, timeout=30.0) as c:
        yield c
