CONFTEST_TEMPLATE = '''"""Auto-generated by apitest — test fixtures."""
import os
import pytest
import httpx


@pytest.fixture(scope="session")
def base_url():
    return os.environ.get("APITEST_BASE_URL", "{base_url}")


@pytest.fixture(scope="session")
def auth_token():
    token = os.environ.get("APITEST_AUTH_TOKEN", "")
    if not token:
        pytest.skip("APITEST_AUTH_TOKEN not set")
    return token


@pytest.fixture
def client(base_url):
    with httpx.Client(base_url=base_url, timeout=30.0) as c:
        yield c
'''
