import json
import re
import subprocess
import sys
from pathlib import Path

from apitest.engine.conftest_template import CONFTEST_TEMPLATE


class TestRunner:
    """Generates test code and runs pytest with allure."""

    def __init__(self, config):
        self.config = config
        self._test_dir = Path("apitest_tests")

    def run(self, examples, plan, mode, mock_server=None):
        self._test_dir.mkdir(exist_ok=True)

        # Clean stale test files from previous runs
        for old in self._test_dir.glob("test_*.py"):
            old.unlink()

        base_url = self.config.base_url
        if mode == "mock" and mock_server:
            base_url = mock_server.url

        write_conftest(str(self._test_dir), base_url)

        test_files = _group_by_resource(examples)
        for resource, resource_examples in test_files.items():
            code = generate_pytest_file(resource, resource_examples, base_url)
            filepath = self._test_dir / f"test_{resource}.py"
            filepath.write_text(code)

        Path("allure-results").mkdir(exist_ok=True)

        cmd = [
            sys.executable, "-m", "pytest",
            str(self._test_dir),
            "--alluredir", self.config.report_dir,
            "-v",
        ]
        result = subprocess.run(cmd, cwd=str(Path.cwd()))
        return result.returncode


def write_conftest(dir_path: str, base_url: str) -> None:
    content = CONFTEST_TEMPLATE.format(base_url=base_url)
    Path(dir_path, "conftest.py").write_text(content)


def _py_repr(val) -> str:
    """Convert a Python value to its source code representation (True/False/None, not true/false/null)."""
    if val is True:
        return "True"
    if val is False:
        return "False"
    if val is None:
        return "None"
    if isinstance(val, str):
        return json.dumps(val)
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, dict):
        items = ", ".join(f"{_py_repr(k)}: {_py_repr(v)}" for k, v in val.items())
        return "{" + items + "}"
    if isinstance(val, list):
        items = ", ".join(_py_repr(v) for v in val)
        return "[" + items + "]"
    return json.dumps(val)


def _resolve_path(path: str) -> str:
    """Replace OpenAPI path parameters {param} or ${param} with test-friendly values."""
    return re.sub(r'\$\{(\w+)\}|\{(\w+)\}', r'1', path)


def generate_pytest_file(resource: str, examples, base_url: str) -> str:
    lines = [
        '"""Auto-generated by apitest."""',
        "import json",
        "import allure",
        "",
        "",
        f"class Test{resource.title()}:",
        f'    """Tests for {resource} endpoints."""',
        "",
    ]

    for example in examples:
        test_name = _to_test_name(example)
        method, raw_path = example.endpoint.split(" ", 1)
        http_method = method.lower()
        path = _resolve_path(raw_path)
        feature = resource.title()
        story = example.description

        lines.append(f"    @allure.feature('{_escape_py_str(feature)}')")
        lines.append(f"    @allure.story('{_escape_py_str(story)}')")
        lines.append(f"    def {test_name}(self, client, auth_token):")

        # Build headers
        headers = {}
        for k, v in example.request_headers.items():
            val = re.sub(r'\$\{\w+\}', '{auth_token}', v)
            headers[k] = val

        if headers:
            headers_str = ", ".join(f'"{k}": f"{v}"' for k, v in headers.items())
            lines.append(f"        headers = {{{headers_str}}}")
        else:
            lines.append("        headers = {}")

        # Auto-add Content-Type for requests with body
        if http_method in ("post", "put", "patch") and example.request_body:
            if "Content-Type" not in headers:
                lines.append('        headers["Content-Type"] = "application/json"')

        # Resolve ${VAR} patterns in request body values
        body = example.request_body
        if body and isinstance(body, dict):
            body = {}
            for k, v in (example.request_body or {}).items():
                if isinstance(v, str):
                    body[k] = re.sub(r'\$\{\w+\}', 'test_value', v)
                else:
                    body[k] = v
        if http_method in ("get", "head", "options"):
            lines.append(f"        res = client.{http_method}('{path}', headers=headers)")
        elif http_method == "delete":
            if body:
                body_str = _py_repr(body)
                lines.append(f"        res = client.request('DELETE', '{path}', headers=headers, json={body_str})")
            else:
                lines.append(f"        res = client.{http_method}('{path}', headers=headers)")
        else:  # post, put, patch
            if body:
                body_str = _py_repr(body)
                lines.append(f"        res = client.{http_method}('{path}', headers=headers, json={body_str})")
            else:
                lines.append(f"        res = client.{http_method}('{path}', headers=headers)")

        # Status assertion
        lines.append(f"        assert res.status_code == {example.expected_status}")

        # Response body: verify basic structure (schema-driven, not LLM-driven)
        lines.append("        body = res.json()")
        lines.append("        assert body is not None, 'Response body should not be empty'")
        lines.append("        # Check wrapped response envelope if present")
        lines.append("        if isinstance(body, dict) and 'code' in body:")
        lines.append("            assert body['code'] == 200, f'Expected code 200, got {body.get(\"code\")}'")
        lines.append("        if isinstance(body, dict) and 'data' in body:")
        lines.append("            assert body['data'] is not None, 'data field should not be null'")
        for field in example.expected_body_contains:
            lines.append(f"        # Field check: response should contain data related to '{_escape_py_str(field)}'")

        # Response time assertion
        lines.append(f"        assert res.elapsed.total_seconds() < {example.max_response_time_ms / 1000}")
        lines.append("")

    return "\n".join(lines)


def _group_by_resource(examples):
    groups = {}
    for e in examples:
        method, path = e.endpoint.split(" ", 1)
        # Strip query params from path
        path = path.split("?")[0]
        parts = [p for p in path.split("/") if p and not p.startswith("{") and not p.startswith("$")]
        resource = parts[-1] if parts else "root"
        groups.setdefault(resource, []).append(e)
    return groups


def _escape_py_str(s: str) -> str:
    """Escape a string for safe use in Python single-quoted string literals."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def _to_test_name(example):
    # Use example ID for uniqueness, description for readability
    name = example.description.lower()
    name = re.sub(r"[^a-z0-9 ]", "", name)
    name = re.sub(r"\s+", "_", name).strip("_")
    if not name:
        # Chinese or other non-ASCII descriptions — use endpoint method+path
        endpoint_slug = example.endpoint.lower().replace(" ", "_").replace("/", "_").strip("_")
        name = endpoint_slug
    return f"test_{example.id.lower().replace('-', '_')}"
