import re
import subprocess
import sys
from pathlib import Path

from apitest.engine.conftest_template import CONFTEST_TEMPLATE


class TestRunner:
    """Generates test code and runs pytest with allure."""

    def __init__(self, config):
        self.config = config
        self._test_dir = Path("apitest_tests")

    def run(self, examples, plan, mode, mock_server=None):
        self._test_dir.mkdir(exist_ok=True)

        base_url = self.config.base_url
        if mode == "mock" and mock_server:
            base_url = mock_server.url

        write_conftest(str(self._test_dir), base_url)

        test_files = _group_by_resource(examples)
        for resource, resource_examples in test_files.items():
            code = generate_pytest_file(resource, resource_examples, base_url)
            filepath = self._test_dir / f"test_{resource}.py"
            filepath.write_text(code)

        Path("allure-results").mkdir(exist_ok=True)

        cmd = [
            sys.executable, "-m", "pytest",
            str(self._test_dir),
            "--alluredir", self.config.report_dir,
            "-v",
        ]
        result = subprocess.run(cmd, cwd=str(Path.cwd()))
        return result.returncode


def write_conftest(dir_path: str, base_url: str) -> None:
    content = CONFTEST_TEMPLATE.format(base_url=base_url)
    Path(dir_path, "conftest.py").write_text(content)


def generate_pytest_file(resource: str, examples, base_url: str) -> str:
    import json

    lines = [
        '"""Auto-generated by apitest."""',
        "import allure",
        "",
        "",
        f"class Test{resource.title()}:",
        f'    """Tests for {resource} endpoints."""',
        "",
    ]

    for example in examples:
        test_name = _to_test_name(example)
        method, path = example.endpoint.split(" ", 1)
        http_method = method.lower()
        feature = resource.title()
        story = example.description

        lines.append(f"    @allure.feature('{_escape_py_str(feature)}')")
        lines.append(f"    @allure.story('{_escape_py_str(story)}')")
        lines.append(f"    def {test_name}(self, client, auth_token):")

        headers = {}
        for k, v in example.request_headers.items():
            # Replace all ${VAR} patterns with auth_token reference
            val = re.sub(r'\$\{\w+\}', '{auth_token}', v)
            headers[k] = val

        headers_str = ", ".join(
            f'"{k}": f"{v}"' for k, v in headers.items()
        )
        lines.append(f"        headers = {{{headers_str}}}")

        if http_method in ("get", "delete", "head", "options"):
            if example.request_body:
                lines.append(
                    f"        res = client.{http_method}('{path}', headers=headers, json={example.request_body})"
                )
            else:
                lines.append(
                    f"        res = client.{http_method}('{path}', headers=headers)"
                )
        else:
            body = example.request_body or {}
            body_str = json.dumps(body)
            lines.append(
                f"        res = client.{http_method}('{path}', headers=headers, json={body_str})"
            )

        lines.append(
            f"        assert res.status_code == {example.expected_status}"
        )
        for field in example.expected_body_contains:
            lines.append(f"        assert '{_escape_py_str(field)}' in res.json()")
        lines.append(
            f"        assert res.elapsed.total_seconds() < {example.max_response_time_ms / 1000}"
        )
        lines.append("")

    return "\n".join(lines)


def _group_by_resource(examples):
    groups = {}
    for e in examples:
        method, path = e.endpoint.split(" ", 1)
        parts = [p for p in path.split("/") if p and not p.startswith("{")]
        resource = parts[-1] if parts else "root"
        groups.setdefault(resource, []).append(e)
    return groups


def _escape_py_str(s: str) -> str:
    """Escape a string for safe use in Python single-quoted string literals."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def _to_test_name(example):
    import re

    name = example.description.lower()
    name = re.sub(r"[^a-z0-9 ]", "", name)
    name = re.sub(r"\s+", "_", name).strip("_")
    return f"test_{name}"
